# Generated by Django 5.2.5 on 2026-02-14 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.PositiveSmallIntegerField()),
                ("commentaire", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "compagnie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avis",
                        to="transport.compagnietransport",
                    ),
                ),
                (
                    "profil_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avis",
                        to="accounts.profilclient",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avis",
                        to="transport.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
            },
        ),
        migrations.CreateModel(
            name="TicketSAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert"),
                            ("EN_COURS", "En cours"),
                            ("RESOLU", "Résolu"),
                            ("FERME", "Fermé"),
                        ],
                        default="OUVERT",
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                (
                    "profil_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets_sav",
                        to="accounts.profilclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket SAV",
                "verbose_name_plural": "Tickets SAV",
            },
        ),
        migrations.CreateModel(
            name="MessageSAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auteur_client", models.BooleanField(default=True)),
                ("contenu", models.TextField()),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="sav_aavis.ticketsav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message SAV",
                "verbose_name_plural": "Messages SAV",
            },
        ),
    ]
