# Generated by Django 6.0.2 on 2026-09-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profilemploye_compagnie_profilemploye_company"),
        ("iam", "0005_permission_resources_company_ligne_audit"),
        ("sav_aavis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagesav",
            options={
                "ordering": ["cree_le"],
                "verbose_name": "Message SAV",
                "verbose_name_plural": "Messages SAV",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketsav",
            options={
                "ordering": ["-cree_le"],
                "verbose_name": "Ticket SAV",
                "verbose_name_plural": "Tickets SAV",
            },
        ),
        migrations.AddField(
            model_name="ticketsav",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="ticketsav",
            name="client_nom",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="ticketsav",
            name="client_telephone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="ticketsav",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets_sav",
                to="iam.company",
            ),
        ),
        migrations.AddField(
            model_name="ticketsav",
            name="numero_billet",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="ticketsav",
            name="priorite",
            field=models.CharField(
                choices=[
                    ("BASSE", "Basse"),
                    ("MOYENNE", "Moyenne"),
                    ("HAUTE", "Haute"),
                ],
                default="MOYENNE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ticketsav",
            name="profil_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_sav",
                to="accounts.profilclient",
            ),
        ),
    ]
