/** Barrel des composants shadcn — préférer les imports directs `@/components/ui/<nom>`. */
export { Button, buttonVariants } from './button'
export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent } from './card'
export { Input } from './input'
export { Badge, badgeVariants } from './badge'
export { Label } from './label'
export { Textarea } from './textarea'
export { Separator } from './separator'
export { Skeleton } from './skeleton'
export { Spinner } from './spinner'
export { Switch } from './switch'
export { Checkbox } from './checkbox'
export { Progress } from './progress'
export { Tabs, TabsList, TabsTrigger, TabsContent } from './tabs'
export { Table, TableHeader, TableBody, TableFooter, TableHead, TableRow, TableCell, TableCaption } from './table'
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from './dialog'
export { Alert, AlertTitle, AlertDescription, AlertAction } from './alert'
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from './alert-dialog'
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue } from './select'
export { Sheet, SheetTrigger, SheetClose, SheetContent, SheetHeader, SheetFooter, SheetTitle, SheetDescription } from './sheet'
export { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuShortcut } from './dropdown-menu'
export { Popover, PopoverTrigger, PopoverContent } from './popover'
export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from './tooltip'
export { Avatar, AvatarImage, AvatarFallback } from './avatar'
export { ScrollArea, ScrollBar } from './scroll-area'
export { Toaster } from './sonner'
export { SidebarProvider, Sidebar, SidebarTrigger, SidebarInset, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarGroup, SidebarGroupLabel } from './sidebar'
