# Generated by Django 5.2.5 on 2026-02-14 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil client",
                "verbose_name_plural": "Profils clients",
            },
        ),
        migrations.CreateModel(
            name="ContactConfiance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                ("telephone", models.CharField(max_length=30)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("PARENT", "Parent"),
                            ("AMI", "Ami"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                    ),
                ),
                ("requis_si_mineur", models.BooleanField(default=False)),
                (
                    "profil_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts_confiance",
                        to="accounts.profilclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact de confiance",
                "verbose_name_plural": "Contacts de confiance",
            },
        ),
    ]
