# Generated by Django 5.2.5 on 2026-02-14 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("transport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilEmploye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN_PLATEFORME", "Admin plateforme"),
                            ("CHEF_COMPAGNIE", "Chef de compagnie"),
                            ("CONTROLEUR", "Contrôleur (scan)"),
                            ("RECEPTIONNISTE", "Réceptionniste"),
                            ("COMPTABLE", "Comptable"),
                            ("SAV", "SAV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "compagnie",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionnel pour l'admin plateforme.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employes",
                        to="transport.compagnietransport",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_employe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil employé",
                "verbose_name_plural": "Profils employés",
            },
        ),
    ]
