# Generated by Django 6.0.2 on 2026-03-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilemploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemploye',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
