# Generated by Django 5.2.4 on 2026-09-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profilemploye_telephone"),
        ("iam", "0002_alter_customuser_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilemploye",
            name="compagnie",
        ),
        migrations.AddField(
            model_name="profilemploye",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionnel pour le Super Admin plateforme.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employes",
                to="iam.company",
            ),
        ),
    ]
