# Generated by Django 5.2.5 on 2026-02-14 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("EMAIL", "Email"), ("PUSH", "Push")],
                        max_length=10,
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ENVOYEE", "Envoyée"),
                            ("ECHOUEE", "Échouée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                ("envoye_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
                (
                    "profil_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.profilclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "indexes": [
                    models.Index(
                        fields=["profil_client", "cree_le"],
                        name="notificatio_profil__b3e427_idx",
                    ),
                    models.Index(
                        fields=["statut", "canal"], name="notificatio_statut_1d9c2a_idx"
                    ),
                ],
            },
        ),
    ]
