# Generated by Django 5.2.4 on 2026-09-13 09:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_alter_customuser_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="new_values",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_values",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
