# Generated by Django 5.2.4 on 2026-09-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_alter_auditlog_new_values_alter_auditlog_old_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="iam.company",
            ),
        ),
    ]
