# Generated by Django 5.2.4 on 2026-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0004_alter_auditlog_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="resource",
            field=models.CharField(
                choices=[
                    ("company", "Compagnie"),
                    ("gare", "Gare"),
                    ("bus", "Bus"),
                    ("ligne", "Ligne"),
                    ("trajet", "Trajet"),
                    ("tarif", "Tarif"),
                    ("employe", "Employé"),
                    ("billet", "Billet"),
                    ("paiement", "Paiement"),
                    ("rapport", "Rapport"),
                    ("iam", "IAM"),
                    ("audit", "Audit"),
                    ("dashboard", "Dashboard"),
                ],
                max_length=50,
            ),
        ),
    ]
