# Generated by Django 5.2.5 on 2026-02-14 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRMEE", "Confirmée"),
                            ("ANNULEE", "Annulée"),
                            ("EXPIREE", "Expirée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                ("montant_total", models.PositiveIntegerField(default=0)),
                ("devise", models.CharField(default="XOF", max_length=10)),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("confirme_le", models.DateTimeField(blank=True, null=True)),
                (
                    "profil_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="accounts.profilclient",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="transport.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
            },
        ),
        migrations.CreateModel(
            name="Billet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_qr", models.CharField(max_length=120, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EMIS", "Émis"),
                            ("SCANNE", "Scanné"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EMIS",
                        max_length=10,
                    ),
                ),
                ("emis_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("scanne_le", models.DateTimeField(blank=True, null=True)),
                (
                    "siege",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billets",
                        to="transport.siege",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billet",
                        to="reservation_billets.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billet",
                "verbose_name_plural": "Billets",
            },
        ),
    ]
