# Generated by Django 5.2.5 on 2026-02-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profilemploye"),
        ("reservation_billets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billet",
            name="scanne_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billets_scannes",
                to="accounts.profilemploye",
            ),
        ),
    ]
