# Generated by Django 5.2.4 on 2026-09-12 19:33

import apps.reservation_billets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_billets", "0004_billet_piece_identite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billet",
            options={
                "ordering": ["-emis_le"],
                "verbose_name": "Billet",
                "verbose_name_plural": "Billets",
            },
        ),
        migrations.AlterField(
            model_name="billet",
            name="numero_billet",
            field=models.CharField(
                default=apps.reservation_billets.models._generer_numero,
                max_length=30,
                unique=True,
            ),
        ),
    ]
