# Generated by Django 5.2.5 on 2026-02-14 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservation_billets", "0001_initial"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LienPartagePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone_destinataire", models.CharField(max_length=30)),
                ("jeton", models.CharField(max_length=64, unique=True)),
                ("actif", models.BooleanField(default=True)),
                ("expire_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "billet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_partage",
                        to="reservation_billets.billet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de partage de position",
                "verbose_name_plural": "Liens de partage de position",
                "indexes": [
                    models.Index(
                        fields=["actif", "expire_le"],
                        name="suivis_temp_actif_fe3b04_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PositionTrajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "vitesse_kmh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "enregistre_le",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="transport.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position de trajet",
                "verbose_name_plural": "Positions de trajet",
                "indexes": [
                    models.Index(
                        fields=["trajet", "enregistre_le"],
                        name="suivis_temp_trajet__1a8a5f_idx",
                    )
                ],
            },
        ),
    ]
