// Styles sombres partagés pour tous les formulaires de l'application
export function darkFormStyles() {
  return {
    page: {
      minHeight: "100vh",
      backgroundColor: "#0D1117",
      fontFamily: "'Segoe UI', Arial, sans-serif",
    },
    main: {
      maxWidth: "560px",
      margin: "0 auto",
      padding: "32px 20px 48px",
    },
    card: {
      backgroundColor: "#161B22",
      borderRadius: "14px",
      padding: "32px",
      boxShadow: "0 4px 20px rgba(0,0,0,0.4)",
      borderLeft: "4px solid #C41E3A",
    },
    group: {
      marginBottom: "20px",
    },
    label: {
      display: "block",
      fontSize: "12px",
      fontWeight: "700",
      color: "#8B949E",
      textTransform: "uppercase",
      letterSpacing: "0.8px",
      marginBottom: "8px",
    },
    input: {
      width: "100%",
      padding: "12px 14px",
      fontSize: "15px",
      borderRadius: "10px",
      border: "1.5px solid #30363D",
      backgroundColor: "#21262D",
      color: "#E6EDF3",
      boxSizing: "border-box",
      outline: "none",
      fontFamily: "inherit",
    },
    inputReadonly: {
      width: "100%",
      padding: "12px 14px",
      fontSize: "15px",
      borderRadius: "10px",
      border: "1.5px solid #21262D",
      backgroundColor: "#0D1117",
      color: "#6E7681",
      boxSizing: "border-box",
      outline: "none",
      fontFamily: "inherit",
    },
    btnRow: {
      display: "flex",
      gap: "12px",
      justifyContent: "center",
      marginTop: "8px",
    },
    btnSubmit: {
      padding: "12px 28px",
      fontSize: "15px",
      fontWeight: "700",
      color: "#fff",
      backgroundColor: "#009A44",
      border: "none",
      borderRadius: "8px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    btnBack: {
      padding: "12px 28px",
      fontSize: "15px",
      fontWeight: "600",
      color: "#E6EDF3",
      backgroundColor: "#21262D",
      border: "1.5px solid #30363D",
      borderRadius: "8px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    error: {
      backgroundColor: "#2D1117",
      border: "1px solid #C41E3A",
      borderRadius: "8px",
      padding: "10px 14px",
      color: "#FF7B72",
      fontSize: "14px",
      marginBottom: "16px",
    },
    success: {
      backgroundColor: "#112D1F",
      border: "1px solid #009A44",
      borderRadius: "8px",
      padding: "10px 14px",
      color: "#56D364",
      fontSize: "14px",
      marginBottom: "16px",
    },
  };
}
