// Thème clair partagé (Poppins + palette navy / bleu / teal)
export function darkFormStyles() {
  return {
    page: {
      minHeight: "100vh",
      backgroundColor: "#F5F7FA",
      fontFamily: "'Poppins', 'Segoe UI', sans-serif",
    },
    main: {
      maxWidth: "560px",
      margin: "0 auto",
      padding: "32px 20px 48px",
    },
    card: {
      backgroundColor: "#FFFFFF",
      borderRadius: "18px",
      padding: "32px",
      boxShadow: "0 8px 28px rgba(26, 19, 72, 0.08)",
      border: "1px solid #E5E7EB",
      borderLeft: "4px solid #304FFE",
    },
    group: {
      marginBottom: "20px",
    },
    label: {
      display: "block",
      fontSize: "12px",
      fontWeight: "700",
      color: "#6B7280",
      textTransform: "uppercase",
      letterSpacing: "0.8px",
      marginBottom: "8px",
    },
    input: {
      width: "100%",
      padding: "12px 14px",
      fontSize: "15px",
      borderRadius: "14px",
      border: "1.5px solid #E5E7EB",
      backgroundColor: "#FFFFFF",
      color: "#1A1348",
      boxSizing: "border-box",
      outline: "none",
      fontFamily: "inherit",
    },
    inputReadonly: {
      width: "100%",
      padding: "12px 14px",
      fontSize: "15px",
      borderRadius: "14px",
      border: "1.5px solid #E5E7EB",
      backgroundColor: "#F5F7FA",
      color: "#6B7280",
      boxSizing: "border-box",
      outline: "none",
      fontFamily: "inherit",
    },
    btnRow: {
      display: "flex",
      gap: "12px",
      justifyContent: "center",
      marginTop: "8px",
    },
    btnSubmit: {
      padding: "12px 28px",
      fontSize: "15px",
      fontWeight: "700",
      color: "#fff",
      backgroundColor: "#26C2A1",
      border: "none",
      borderRadius: "14px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    btnBack: {
      padding: "12px 28px",
      fontSize: "15px",
      fontWeight: "600",
      color: "#1A1348",
      backgroundColor: "#F5F7FA",
      border: "1.5px solid #E5E7EB",
      borderRadius: "14px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    error: {
      backgroundColor: "#FFF1F2",
      border: "1px solid #E11D48",
      borderRadius: "12px",
      padding: "10px 14px",
      color: "#E11D48",
      fontSize: "14px",
      marginBottom: "16px",
    },
    success: {
      backgroundColor: "#E6F9F5",
      border: "1px solid #26C2A1",
      borderRadius: "12px",
      padding: "10px 14px",
      color: "#0F766E",
      fontSize: "14px",
      marginBottom: "16px",
    },
  };
}
