# Generated by Django 5.2.5 on 2026-02-14 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservation_billets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.PositiveIntegerField(default=0)),
                ("devise", models.CharField(default="XOF", max_length=10)),
                (
                    "fournisseur",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("ADYEN", "Adyen"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                    ),
                ),
                (
                    "identifiant_fournisseur",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CAPTURE", "Capturé"),
                            ("ECHOUE", "Échoué"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("capture_le", models.DateTimeField(blank=True, null=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiement",
                        to="reservation_billets.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
            },
        ),
    ]
