# Generated by Django 5.2.5 on 2026-02-14 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompagnieTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Compagnie de transport",
                "verbose_name_plural": "Compagnies de transport",
            },
        ),
        migrations.CreateModel(
            name="Arret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("ville", models.CharField(blank=True, max_length=150)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrêt",
                "verbose_name_plural": "Arrêts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nom", "ville"), name="uniq_arret_nom_ville"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immatriculation", models.CharField(max_length=50, unique=True)),
                (
                    "type_bus",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("VIP", "VIP")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("capacite", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus",
                        to="transport.compagnietransport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus",
                "verbose_name_plural": "Bus",
            },
        ),
        migrations.CreateModel(
            name="Ligne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_arrivee",
                        to="transport.arret",
                    ),
                ),
                (
                    "origine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_depart",
                        to="transport.arret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne",
                "verbose_name_plural": "Lignes",
            },
        ),
        migrations.CreateModel(
            name="Siege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sieges",
                        to="transport.bus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Siège",
                "verbose_name_plural": "Sièges",
            },
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bus",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("VIP", "VIP")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "prix",
                    models.PositiveIntegerField(
                        help_text="Montant en plus petite unité (ex: francs)."
                    ),
                ),
                ("devise", models.CharField(default="XOF", max_length=10)),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="transport.compagnietransport",
                    ),
                ),
                (
                    "ligne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="transport.ligne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tarifs",
            },
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart_prevu", models.DateTimeField()),
                ("arrivee_prevue", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifié"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="PLANIFIE",
                        max_length=15,
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trajets",
                        to="transport.bus",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trajets",
                        to="transport.compagnietransport",
                    ),
                ),
                (
                    "ligne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trajets",
                        to="transport.ligne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
            },
        ),
        migrations.AddConstraint(
            model_name="ligne",
            constraint=models.UniqueConstraint(
                fields=("origine", "destination"), name="uniq_ligne_od"
            ),
        ),
        migrations.AddConstraint(
            model_name="siege",
            constraint=models.UniqueConstraint(
                fields=("bus", "numero"), name="uniq_siege_par_bus"
            ),
        ),
        migrations.AddConstraint(
            model_name="tarif",
            constraint=models.UniqueConstraint(
                fields=("compagnie", "ligne", "type_bus"),
                name="uniq_tarif_compagnie_ligne_type",
            ),
        ),
    ]
