# Generated by Django 5.2.4 on 2026-09-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_alter_customuser_company"),
        ("transport", "0003_trajet_controleur"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tarif",
            name="uniq_tarif_segment",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="compagnie",
        ),
        migrations.RemoveField(
            model_name="ligne",
            name="compagnie",
        ),
        migrations.RemoveField(
            model_name="tarif",
            name="compagnie",
        ),
        migrations.RemoveField(
            model_name="trajet",
            name="compagnie",
        ),
        migrations.AddField(
            model_name="bus",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus",
                to="iam.company",
            ),
        ),
        migrations.AddField(
            model_name="ligne",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="iam.company",
            ),
        ),
        migrations.AddField(
            model_name="tarif",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="iam.company",
            ),
        ),
        migrations.AddField(
            model_name="trajet",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trajets",
                to="iam.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarif",
            constraint=models.UniqueConstraint(
                fields=("ligne", "arret_depart", "arret_arrivee", "type_bus"),
                name="uniq_tarif_segment",
            ),
        ),
    ]
