# Generated by Django 5.2.4 on 2026-09-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profilemploye_compagnie_profilemploye_company"),
        ("iam", "0005_permission_resources_company_ligne_audit"),
        (
            "transport",
            "0004_remove_tarif_uniq_tarif_segment_remove_bus_compagnie_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HoraireLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heure_depart", models.TimeField()),
                ("jours", models.CharField(default="0,1,2,3,4,5,6", max_length=20)),
                (
                    "type_bus",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("VIP", "VIP")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "duree_estimee_min",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Durée estimée en minutes pour calculer arrivee_prevue.",
                        null=True,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "bus_defaut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horaires_defaut",
                        to="transport.bus",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horaires",
                        to="iam.company",
                    ),
                ),
                (
                    "ligne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horaires",
                        to="transport.ligne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horaire de ligne",
                "verbose_name_plural": "Horaires de ligne",
                "ordering": ["ligne", "heure_depart"],
            },
        ),
        migrations.AddField(
            model_name="trajet",
            name="horaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trajets",
                to="transport.horaireligne",
            ),
        ),
        migrations.AddConstraint(
            model_name="trajet",
            constraint=models.UniqueConstraint(
                fields=("ligne", "depart_prevu"), name="uniq_trajet_ligne_depart"
            ),
        ),
    ]
